first stage rewrite for multiple backup servers (still need to sort out ssh keys)

diff --git a/templates/backup-script.erb b/templates/backup-script.erb
--- a/templates/backup-script.erb
+++ b/templates/backup-script.erb
@@ -2,108 +2,120 @@
 
 # This backup script is managed by PUPPET
 
-# Variables
-BACKUP_DEST=backups@<%= backup_server %>
-FQDN=`hostname -f`
-EXIT_STATUS=0
-LOGFILE=/tmp/$FQDN-`date --iso`.log
-
-# Get the number 1 or 0, based on the day of week
-# so we at least get a backup for yesterday and today
-DAY_OF_WEEK_NUM=`date "+%u"`
-MODULO=`expr ${DAY_OF_WEEK_NUM} % 2`
-
-IONICE=`/usr/bin/which ionice`
-if [ -n "$IONICE" ] ; then
-	IONICE="$IONICE -c3"
-fi
-
-# Functions
-log_info() {
-	logger -t $0 -p local0.notice -i "[info] $@" ; echo "`date` $@" >> $LOGFILE
-}
-
-log_error () {
-	logger -t $0 -p local0.err -i "[error] $@" ; echo "`date` $@" >> $LOGFILE
-}
-
-log_warn () {
-	logger -t $0 -p local0.warning -i "[warning] $0" ; echo "`date` $@" >> $LOGFILE
-}
-
-log_info "Starting backup script"
-
-log_info "Backing up to $BACKUP_DEST"
-
-# Get the list of mounted filsystems,
-# but don't backup the filesystems named:
-# backup|xenguests|home|srbdata|squid
-FILESYSTEMS=`mount -l -t xfs,ext4,ext3,ext2,simfs | awk '{print $3}' | egrep -iv "backup|xenguests|home|srbdata|squid"`
- 
-log_info "Backing up filesystems: $FILESYSTEMS"
-
-for FILESYSTEM in $FILESYSTEMS; do
-
-	# Get the size of the FS in 1GB blocks
-	SIZE=`df -B 1073741824 -P ${FILESYSTEM} | grep ${FILESYSTEM} | awk '{print $2}'`
-
-	# Don't backup filesystems greater than 249GB
-	if [ $SIZE -gt 249 ]; then
-		log_warn "Skipping ${FILESYSTEM}: size is greater than 249GB"
-		continue
-	fi
-
-	# If the FS is / then add 'root' to the filename
-	if [ "$FILESYSTEM" == "/" ]; then
-		FS_NAME="_root"
-	else
-		FS_NAME=`echo $FILESYSTEM | tr '/' '_'`
-	fi
-			
-	# Define the backup file, which will look like
-	#   staff.vpac.org_root_0.tar.gz
-	BACKUP_FILE=${FQDN}${FS_NAME}_${MODULO}.tar.gz
-	
-	# Output status message
-	log_info "Filesystem $FILESYSTEM => $BACKUP_FILE"
-	
-	# Generate the exclude list
-	cd $FILESYSTEM || continue
-	( [ "$FILESYSTEM" = / ] && find ./tmp -mount ! -name tmp 2>/dev/null; echo "./tmp/$BACKUP_FILE" || cat /dev/null ) >/tmp/exc.$$
-	
-	# Remove the old backup file from the server
-	ssh $BACKUP_DEST "rm -f $BACKUP_FILE"
-	
-	# Create the new backup file
-	$IONICE nice tar -czf $BACKUP_DEST:$BACKUP_FILE --one-file-system --ignore-failed-read --rsh-command=/usr/bin/ssh -X /tmp/exc.$$ . 2>&1 | grep -v "socket ignored" | grep -v "file changed as we read it" | grep -v "Cannot stat: No such file or directory" | grep -v "File removed before we read it"
-	
-	# Check exit status of tar file
-	if [ $? -gt 1 ]; then 
-		log_err "$FILESYSTEM => Backup failed."
-		EXIT_STATUS=1
-		continue
-	else 
-		log_info "$FILESYSTEM => Backup completed."
-	fi
-	
-	# Remove the temp exclude file
-	rm /tmp/exc.$$
-
-done
-
-log_info "Backup script completed."
-
 mkdir -p /var/log/backups
-mv $LOGFILE /var/log/backups
 
-# Delete backup log files older than 30 days
-cd /var/log/backups; find . -maxdepth 1 -name "*.log" -ctime +30 -exec rm -f {} +
+# user variables
+backup_servers=<% backup_servers.each do |server| %>backups@<%= server %> <%end %>
+logfile=/var/log/backups/$FQDN-`date --iso`.log
+max_fs_size=249
 
-if [ $EXIT_STATUS -eq 1 ]
-then
-	cat $LOGFILE
+# modulo is the number of days backups to keep on the server
+day_num=`date "+%u"`
+modulo=`expr ${day_num} % 3`
+
+# check for ionice and use it if found
+ionice=`/usr/bin/which ionice`
+if [ -n "$ionice" ] ; then
+  ionice="$ionice -c3"
 fi
 
-exit $EXIT_STATUS
+function log_info() {
+  logger -t $0 -p local0.notice -i "[info] $@" ; echo "`date` $@" >> $logfile
+}
+
+function log_error () {
+  logger -t $0 -p local0.err -i "[error] $@" ; echo "`date` $@" >> $logfile
+}
+
+function log_warn () {
+  logger -t $0 -p local0.warning -i "[warning] $0" ; echo "`date` $@" >> $logfile
+}
+
+function backup_fs () {
+
+  # get the size of the FS in 1GB blocks
+  fs_size=`df -B 1073741824 -P ${fs} | grep ${fs} | awk '{print $3}'`
+
+  # don't backup filesystems using more than $max_fs_size
+  if [ ${fs_size} -gt ${max_fs_size} ]; then
+    log_warn "Skipping ${fs}: size is greater than ${max_fs_size}GB"
+    continue
+  fi
+
+  # if the filesystem is / then add 'root' to the filename
+  if [ "${fs}" == "/" ]; then
+    fs_name="_root"
+  else
+    fs_name=`echo ${fs} | tr '/' '_'`
+  fi
+
+  # the backup filename will look like hostname.vpac.org_root_0.tar.gz
+  backup_filename=${fqdn}${fs_name}_${modulo}.tar.gz
+
+  log_info "Filesystem ${fs} => ${backup_filename}"
+
+  # generate the exclude list
+  cd ${fs} || continue
+  ( [ "${fs}" = / ] && find ./tmp -mount ! -name tmp 2>/dev/null; echo "./tmp/${backup_filename}" || cat /dev/null ) >/tmp/exc.$$
+
+  for server in $backup_servers ; do
+
+    log_info "Backing up ${backup_filename} to ${server}"
+
+    # remove the old backup file from the server
+    ssh ${server} "rm -f ${backup_filename}"
+
+    # create the new backup file
+    ${ionice} nice tar -czf ${server}:${backup_filename} --one-file-system --ignore-failed-read --rsh-command=/usr/bin/ssh -X /tmp/exc.$$ . 2>&1 | \
+    grep -v "socket ignored" | \
+    grep -v "file changed as we read it" | \
+    grep -v "Cannot stat: No such file or directory" | \
+    grep -v "File removed before we read it"
+
+    # check exit status of tar process (not the greps)
+    if [ ${PIPESTATUS[0]} -gt 1 ]; then
+      log_err "${fs} => ${server} => Backup failed."
+      rm /tmp/exc.$$
+      exit_status=1
+    else
+      log_info "${fs} => ${server} => Backup completed."
+      rm /tmp/exc.$$
+    fi
+
+  done
+}
+
+
+function main () {
+
+  fqdn=`hostname -f`
+  exit_status=0
+
+  log_info "Starting backup script on ${fqdn}"
+
+  # Get the list of mounted filsystems,  but don't backup the filesystems named:
+  # backup|xenguests|home|srbdata|squid|GMT
+  filesystems=`mount -l -t xfs,ext4,ext3,ext2,simfs | awk '{print $3}' | egrep -iv "backup|xenguests|home|srbdata|squid|GMT"`
+
+  log_info "Backing up filesystems: ${filesystems}"
+
+  for fs in ${filesystems}; do
+    backup_filesystem
+  done
+
+  log_info "Backup script completed."
+
+  # delete backup log files older than 30 days
+  cd `dirname ${logfile}`; find . -maxdepth 1 -name "*.log" -ctime +30 -exec rm -f {} +
+
+  if [ ${exit_status} -gt 1 ] ; then
+    cat ${logfile}
+  fi
+
+  exit ${exit_status}
+
+}
+
+main
 
 # vim:syntax=sh
